<a href="https://colab.research.google.com/github/scxbbard/Data-science-classes/blob/main/HypotestpractZO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#** 🌱Checking whether the fertilizer type affects Growth Miestone 🌱**

In [1]:
###load the dataset
import pandas as pd
df = pd.read_csv('/content/plant_growth_data.csv')

##**Loading the libraries**

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

##**Inspecting the data**

In [2]:
df.head()

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
0,loam,5.192294,bi-weekly,chemical,31.719602,61.591861,0
1,sandy,4.033133,weekly,organic,28.919484,52.422276,1
2,loam,8.892769,bi-weekly,none,23.179059,44.660539,0
3,loam,8.241144,bi-weekly,none,18.465886,46.433227,0
4,sandy,8.374043,bi-weekly,organic,18.128741,63.625923,0

In [3]:
df.tail()

,Soil_Type,Sunlight_Hours,Water_Frequency,Fertilizer_Type,Temperature,Humidity,Growth_Milestone
188,sandy,5.652,daily,none,28.0,70.2,0
189,clay,7.528,weekly,chemical,30.5,60.1,1
190,loam,4.934,bi-weekly,none,24.5,61.7,0
191,sandy,8.273,daily,organic,27.9,69.5,1
192,clay,6.732,weekly,none,21.7,56.9,0

In [4]:
df.shape

(193, 7)

In [6]:
df.columns

Index(['Soil_Type', 'Sunlight_Hours', 'Water_Frequency', 'Fertilizer_Type',
       'Temperature', 'Humidity', 'Growth_Milestone'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Soil_Type         193 non-null    object
 1   Sunlight_Hours    193 non-null    float64
 2   Water_Frequency   193 non-null    object
 3   Fertilizer_Type   193 non-null    object
 4   Temperature       193 non-null    float64
 5   Humidity          193 non-null    float64
 6   Growth_Milestone  193 non-null    int64
dtypes: float64(3), int64(1), object(3)
memory usage: 10.7+ KB

**No null values**

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.describe()

       Sunlight_Hours  Temperature    Humidity  Growth_Milestone
count      193.000000   193.000000  193.000000        193.000000
mean         6.826484    25.076087   58.098927          0.497409
std          1.599509     5.354170   12.631799          0.501294
min          4.033133    15.200000   30.567682          0.000000
25%          5.477000    20.637095   49.300000          0.000000
50%          6.833290    25.912336   59.182806          0.000000
75%          8.241144    29.757938   69.100000          1.000000
max          9.913903    34.810103   79.648240          1.000000

In [11]:
df.describe(include='object')

       Soil_Type Water_Frequency Fertilizer_Type
count        193             193             193
unique         3               3               3
top         clay           daily            none
freq          67              74              74

In [17]:
###Splitting the groups
chem = df[df['Fertilizer_Type'] == 'chemical']['Growth_Milestone']
org = df[df['Fertilizer_Type'] == 'organic']['Growth_Milestone']

In [18]:
chem.head()

0     0
11    0
13    1
15    1
16    0
Name: Growth_Milestone, dtype: int64

In [19]:
org.head()

1    1
4    0
6    1
7    0
9    1
Name: Growth_Milestone, dtype: int64

In [23]:
###Run t_test
t_stat, p_val = stats.ttest_ind(chem, org)

print(f" 🌱t-statistic: {t_stat:.4}")
print(f" 🌱p-value: {p_val:.4}")

 🌱t-statistic: -1.684
 🌱p-value: 0.0948

In [24]:
alpha = 0.05

if p_val < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.